# Generated by Django 4.2 on 2023-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='type',
            field=models.CharField(choices=[('postale', 'Postale'), ('email', 'Email'), ('web', 'Page Web')], max_length=15),
        ),
    ]
