# Generated by Django 4.2 on 2023-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_agenda', '0002_contact_coordinates_alter_coordonnee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='type',
            field=models.CharField(choices=[('postale', 'Postale'), ('telephone', 'Téléphone'), ('email', 'Email'), ('web', 'Page Web')], max_length=15),
        ),
    ]
