# Generated by Django 4.2 on 2023-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_agenda', '0004_alter_agenda_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='name',
            field=models.CharField(default='Agenda par défaut', max_length=255),
            preserve_default=False,
        ),
    ]
