# Generated by Django 4.2 on 2023-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_agenda', '0005_agenda_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordonnee',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='contact',
            name='coordinates',
            field=models.ManyToManyField(related_name='contacts', to='my_agenda.coordonnee'),
        ),
    ]
