# Generated by Django 4.2 on 2023-04-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_agenda', '0007_remove_contact_coordinates_coordonnee_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='my_agenda.contact'),
        ),
    ]
